import Head from 'next/head'
import axios from "axios";
import {NextApiRequest, NextApiResponse} from "next";
import FAQ from "./faq";
import Steps from "./steps";
import Header from "./header";
import Review from "./review";
import Footer from "./footer";
import Gallery from "./gallery";
import AboutUs from "./aboutUs";
import ContactUs from "./contactUs";
import Technologies from "./technologies";

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>WEBTRONICS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <article>
            <AboutUs />
            <Technologies />
            <Steps />
            <FAQ />
            <Review />
            <Gallery />
            <ContactUs />
        </article>
        <Footer />
    </>
  )
}

// export async function getServerSideProps(req: NextApiRequest, res: NextApiResponse) {
//     try {
//         const res = await axios("http://localhost:3004/feedback")
//         const {data} = await res
//         return { props: { data } }
//     } catch (error) {
//         console.error(error)
//         return res.status(500).json({ error })
//     }
// }
